//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:v4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//---
using System;
using APE.Umbraco;
namespace APE.Umbraco.App.Classes.Cms
{
    public partial class UmbBlog 
    {

		public UmbBlog()		
		{
			this.SiteName = new StringProperty(){ Alias = "siteName" };
			this.SiteDescription = new StringProperty(){ Alias = "siteDescription" };
			this.Blogroll = new StringProperty(){ Alias = "blogroll" };
			this.AkismetAPIKey = new StringProperty(){ Alias = "akismetAPIKey" };
			this.Owner = new StringProperty(){ Alias = "owner" };
			this.PingServices = new StringProperty(){ Alias = "pingServices" };
			this.BodyText = new StringProperty(){ Alias = "bodyText" };
				
		}

		public readonly string DocTypeAlias = "umbBlog";

		public static implicit operator string(UmbBlog doctype)
		{
			return "umbBlog";
		}
	 		
				
		/// <summary>
		///		<para>Datatype: Textstring</para>
		/// </summary>
		public StringProperty SiteName { get; private set; }		
				
		/// <summary>
		///		<para>Datatype: Textbox multiple</para>
		/// </summary>
		public StringProperty SiteDescription { get; private set; }		
				
		/// <summary>
		///		<para>Datatype: Related Links</para>
		/// </summary>
		public StringProperty Blogroll { get; private set; }		
				
		/// <summary>
		///		<para>Datatype: Textstring</para>
		///		<para>Description: Enter a valid WP.com API key(http://en.wordpress.com/api-keys/) and your blog will be protected from spam by using the Akismet anti-spam service.</para>
		/// </summary>
		public StringProperty AkismetAPIKey { get; private set; }		
				
		/// <summary>
		///		<para>Datatype: Author Picker</para>
		/// </summary>
		public StringProperty Owner { get; private set; }		
				
		/// <summary>
		///		<para>Datatype: Related Links</para>
		///		<para>Description: Automatically notify blog directories and search engines that your blog has been updated</para>
		/// </summary>
		public StringProperty PingServices { get; private set; }		
				
		/// <summary>
		///		<para>Datatype: Richtext editor</para>
		/// </summary>
		public StringProperty BodyText { get; private set; }
	}
}
