//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:v4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//---
using System;
using APE.Umbraco;
namespace APE.Umbraco.App.Classes.Cms
{
    public partial class UmbBlogPost 
    {

		public UmbBlogPost()		
		{
			this.BodyText = new StringProperty(){ Alias = "bodyText" };
			this.Tags = new StringProperty(){ Alias = "tags" };
			this.CloseComments = new BooleanProperty(){ Alias = "closeComments" };
			this.PostDate = new DateTimeProperty(){ Alias = "PostDate" };
				
		}

		public readonly string DocTypeAlias = "umbBlogPost";

		public static implicit operator string(UmbBlogPost doctype)
		{
			return "umbBlogPost";
		}
	 		
				
		/// <summary>
		///		<para>Datatype: Richtext editor</para>
		/// </summary>
		public StringProperty BodyText { get; private set; }		
				
		/// <summary>
		///		<para>Datatype: Tags</para>
		/// </summary>
		public StringProperty Tags { get; private set; }		
				
		/// <summary>
		///		<para>Datatype: True/false</para>
		/// </summary>
		public BooleanProperty CloseComments { get; private set; }		
				
		/// <summary>
		///		<para>Datatype: Date Picker</para>
		/// </summary>
		public DateTimeProperty PostDate { get; private set; }
	}
}
