//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:v4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//---
using System;
using APE.Umbraco;
namespace APE.Umbraco.App.Classes.Cms
{
    public partial class UmbHomepage 
    {

		public UmbHomepage()		
		{
			this.BodyText = new StringProperty(){ Alias = "bodyText" };
			this.SiteName = new StringProperty(){ Alias = "siteName" };
			this.SiteDescription = new StringProperty(){ Alias = "siteDescription" };
				
		}

		public readonly string DocTypeAlias = "umbHomepage";

		public static implicit operator string(UmbHomepage doctype)
		{
			return "umbHomepage";
		}
	 		
				
		/// <summary>
		///		<para>Datatype: Richtext editor</para>
		/// </summary>
		public StringProperty BodyText { get; private set; }		
				
		/// <summary>
		///		<para>Datatype: Textstring</para>
		/// </summary>
		public StringProperty SiteName { get; private set; }		
				
		/// <summary>
		///		<para>Datatype: Textbox multiple</para>
		/// </summary>
		public StringProperty SiteDescription { get; private set; }
	}
}
