//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:v4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//---
using System;
using APE.Umbraco;
namespace APE.Umbraco.App.Classes.Cms
{
    public partial class UmbNewsArea 
    {

		public UmbNewsArea()		
		{
				
		}

		public readonly string DocTypeAlias = "umbNewsArea";

		public static implicit operator string(UmbNewsArea doctype)
		{
			return "umbNewsArea";
		}
	 
	}
}
