

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:v4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//---
using APE.Umbraco;
namespace APE.Umbraco.App.Classes.Cms
{
	public static class Dictionary
	{
	}
}

//-> DictionaryKeys.cs
// Generated helper templates
// Generated items
// APE.Umbraco\APE.Umbraco.App\Classes\Cms\DictionaryKeys.cs
