

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:v4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//---
namespace APE.Umbraco.App.Classes.Cms
{
    public static class DocTypes
    {
        private static UmbBlog _UmbBlog;
        public static UmbBlog UmbBlog
        {
            get { return _UmbBlog ?? (_UmbBlog = new UmbBlog()); }
        }
        private static UmbBlogPost _UmbBlogPost;
        public static UmbBlogPost UmbBlogPost
        {
            get { return _UmbBlogPost ?? (_UmbBlogPost = new UmbBlogPost()); }
        }
        private static DateFolder _DateFolder;
        public static DateFolder DateFolder
        {
            get { return _DateFolder ?? (_DateFolder = new DateFolder()); }
        }
        private static UmbHomepage _UmbHomepage;
        public static UmbHomepage UmbHomepage
        {
            get { return _UmbHomepage ?? (_UmbHomepage = new UmbHomepage()); }
        }
        private static UmbNewsArea _UmbNewsArea;
        public static UmbNewsArea UmbNewsArea
        {
            get { return _UmbNewsArea ?? (_UmbNewsArea = new UmbNewsArea()); }
        }
        private static UmbNewsArticle _UmbNewsArticle;
        public static UmbNewsArticle UmbNewsArticle
        {
            get { return _UmbNewsArticle ?? (_UmbNewsArticle = new UmbNewsArticle()); }
        }
        private static UmbTextpage _UmbTextpage;
        public static UmbTextpage UmbTextpage
        {
            get { return _UmbTextpage ?? (_UmbTextpage = new UmbTextpage()); }
        }
        private static UmediaSlider _UmediaSlider;
        public static UmediaSlider UmediaSlider
        {
            get { return _UmediaSlider ?? (_UmediaSlider = new UmediaSlider()); }
        }
        private static UmediaSliders _UmediaSliders;
        public static UmediaSliders UmediaSliders
        {
            get { return _UmediaSliders ?? (_UmediaSliders = new UmediaSliders()); }
        }
    }
}

// Generated helper templates
// Generated items
// APE.Umbraco\APE.Umbraco.App\Classes\Cms\UmediaSliders.cs
// APE.Umbraco\APE.Umbraco.App\Classes\Cms\UmediaSlider.cs
// APE.Umbraco\APE.Umbraco.App\Classes\Cms\UmbTextpage.cs
// APE.Umbraco\APE.Umbraco.App\Classes\Cms\UmbNewsArticle.cs
// APE.Umbraco\APE.Umbraco.App\Classes\Cms\UmbNewsArea.cs
// APE.Umbraco\APE.Umbraco.App\Classes\Cms\UmbHomepage.cs
// APE.Umbraco\APE.Umbraco.App\Classes\Cms\DateFolder.cs
// APE.Umbraco\APE.Umbraco.App\Classes\Cms\UmbBlogPost.cs
// APE.Umbraco\APE.Umbraco.App\Classes\Cms\UmbBlog.cs
