//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:v4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//---
using System;
using APE.Umbraco;
namespace APE.Umbraco.App.Classes.Cms
{
    public partial class UmbTextpage 
    {

		public UmbTextpage()		
		{
			this.BodyText = new StringProperty(){ Alias = "bodyText" };
			this.UmbracoNaviHide = new BooleanProperty(){ Alias = "umbracoNaviHide" };
				
		}

		public readonly string DocTypeAlias = "umbTextpage";

		public static implicit operator string(UmbTextpage doctype)
		{
			return "umbTextpage";
		}
	 		
				
		/// <summary>
		///		<para>Datatype: Richtext editor</para>
		/// </summary>
		public StringProperty BodyText { get; private set; }		
				
		/// <summary>
		///		<para>Datatype: True/false</para>
		/// </summary>
		public BooleanProperty UmbracoNaviHide { get; private set; }
	}
}
