//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:v4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//---
using System;
using APE.Umbraco;
namespace APE.Umbraco.App.Classes.Cms
{
    public partial class UmediaSlider 
    {

		public UmediaSlider()		
		{
			this.UmbracoFile = new StringProperty(){ Alias = "umbracoFile" };
			this.TeaserText = new StringProperty(){ Alias = "teaserText" };
			this.Link = new ContentProperty(){ Alias = "link" };
				
		}

		public readonly string DocTypeAlias = "umediaSlider";

		public static implicit operator string(UmediaSlider doctype)
		{
			return "umediaSlider";
		}
	 		
				
		/// <summary>
		///		<para>Datatype: Upload</para>
		/// </summary>
		public StringProperty UmbracoFile { get; private set; }		
				
		/// <summary>
		///		<para>Datatype: Richtext editor</para>
		/// </summary>
		public StringProperty TeaserText { get; private set; }		
				
		/// <summary>
		///		<para>Datatype: Content Picker</para>
		/// </summary>
		public ContentProperty Link { get; private set; }
	}
}
