//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APE.Umbraco.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APE.Umbraco.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [key] FROM [cmsDictionary].
        /// </summary>
        internal static string DictionarySql {
            get {
                return ResourceManager.GetString("DictionarySql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select cpt.Alias as PropertyAlias, cpt.Description as PropertyDescription, cct.Alias as DocType,cct2.Alias as ParentDocType,un3.Text as PropertyType, cdt.propertyEditorAlias as propertyTypeId from umbracoNode un left join cmspropertytype cpt on un.id = cpt.contentTypeId left join cmsdatatype cdt on cpt.dataTypeId = cdt.nodeId inner join cmsContentType cct on un.id = cct.nodeId left join umbracoNode un2 on un2.id = un.parentID left join cmsContentType cct2 on un2.id = cct2.nodeId left join umbracoNode un3 on [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DocTypeSql {
            get {
                return ResourceManager.GetString("DocTypeSql", resourceCulture);
            }
        }
    }
}
